# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: spacex/api/device/dish_config.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#spacex/api/device/dish_config.proto\x12\x11SpaceX.API.Device\"\xc9\x01\n\nDishConfig\x12P\n\x0esnow_melt_mode\x18\x01 \x01(\x0e\x32*.SpaceX.API.Device.DishConfig.SnowMeltModeR\x0csnowMeltMode\x12\x30\n\x14\x61pply_snow_melt_mode\x18\xe9\x07 \x01(\x08R\x11\x61pplySnowMeltMode\"7\n\x0cSnowMeltMode\x12\x08\n\x04\x41UTO\x10\x00\x12\r\n\tALWAYS_ON\x10\x01\x12\x0e\n\nALWAYS_OFF\x10\x02\x42\x17Z\x15spacex.com/api/deviceb\x06proto3')



_DISHCONFIG = DESCRIPTOR.message_types_by_name['DishConfig']
_DISHCONFIG_SNOWMELTMODE = _DISHCONFIG.enum_types_by_name['SnowMeltMode']
DishConfig = _reflection.GeneratedProtocolMessageType('DishConfig', (_message.Message,), {
  'DESCRIPTOR' : _DISHCONFIG,
  '__module__' : 'spacex.api.device.dish_config_pb2'
  # @@protoc_insertion_point(class_scope:SpaceX.API.Device.DishConfig)
  })
_sym_db.RegisterMessage(DishConfig)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\025spacex.com/api/device'
  _DISHCONFIG._serialized_start=59
  _DISHCONFIG._serialized_end=260
  _DISHCONFIG_SNOWMELTMODE._serialized_start=205
  _DISHCONFIG_SNOWMELTMODE._serialized_end=260
# @@protoc_insertion_point(module_scope)
